name: Build
on: [push, pull_request]

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Toolchains
        run: brew install llvm python git ninja &&
             python3 -m ensurepip && git clone https://github.com/cute-engineering/osdk && sudo python3 -m pip install -e osdk/

      - name: Build Core (x86_64)
        run: osdk b core --target=kernel-x86_64

  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Toolchains 
        run: sudo apt-get install clang lld llvm python3 git ninja-build &&
             git clone https://github.com/cute-engineering/osdk -b rewrite && sudo pip install -r osdk/requirements.txt && sudo pip install -e osdk/

      - name: Build Core (x86_64)
        run: osdk b core --target=kernel-x86_64
